pipeline {
    agent any
    tools {
        maven 'maven' 
    }
    stages {
        stage ('Init') {
            steps {
                sh 'echo "Start of Job"'
                sh 'ls -la'
            }
        }
        stage ('Test') {
            steps {
                sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
            }
        }
        stage ('Build') {
            steps {
                sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
            }
        }
        stage ('Deploy to GKE') {
            steps {
                // Authenticate with GKE using configured credentials
                withCredentials([googleServiceAccount(credentialsId: '89769313611', project: 'l4sqairaj')]) {
                    sh 'gcloud container clusters get-credentials your-cluster-name project l4sqairaj'
                }
                
                // Deploy your application to GKE
                sh 'kubectl apply values.yaml'
            }
        }
    }
}
